sonar.projectKey=torrentedge
sonar.organization=torrentedge
sonar.host.url=https://sonarcloud.io

sonar.sources=src,services
sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/downloads/**,**/test-downloads/**,**/logs/**,**/dist/**,**/coverage/**
sonar.test.inclusions=**/*.test.js,**/*.spec.js
